### ISSUE TITLE
Feature request, output value marked as sensitive.

### ISSUE THREAD

**Issue by tristanmorgan** [MorganPeat/terraform-provider-environment#25]
Hi @MorganPeat,

I would like to use the output value of an env-var but have it marked as sensitive. 

Would a separate data source `environment_sensitive_variable` be better or somehow have an attribute to enable sensitive output be preferable? (I'm not the greatest Golang programmer but could wrangle a PR).

Cheers,

T.

similar to [local_sensitive_file](https://registry.terraform.io/providers/hashicorp/local/latest/docs/data-sources/sensitive_file)

**Comment by MorganPeat** [comment]
I did this today, please check. Your suggestion looked spot on to me - have created a new data source `environment_sensitive_variable`.

**Comment by tristanmorgan** [comment]
Thank you so much.
